"use strict";

module.exports = {
  USER_SESSION_VERSION: "1.0.12",
  POST_IMAGES_LIMIT: 4,
  COMMENT_IMAGES_LIMIT: 4,
  STRIKES_EXPIRED_AFTER_X_DAYS: 30,
  STRIKES_COUNT_FOR_BAN: 3,
  STRIKES_BAN_DAYS: 30,
  USERPAGE_HEADER_WIDTH: 2000,
  USERPAGE_HEADER_HEIGHT: 220,
  TEMP_IMAGE_DAY_EXPIRED: 30,
  SPOILED_IMAGE_PATH: "/resources/expired_image.webp",
  UNKNOWN_AVATAR_PATH: "/resources/unknown_avatar.webp",
};
